---
namespace: ericsysmin
name: js
version: 1.1.0
readme: README.md
authors:
  - ericsysmin <eric.sysmin@gmail.com> (http://ericsysmin.com)
description: Ansible collection for JavaScript tools, and libraries
license:
  - MIT
tags:
  - javascript
  - nodejs
  - node
  - yarn
dependencies: {}
repository: https://github.com/ericsysmin/ansible-collection-js
documentation: https://github.com/ericsysmin/ansible-collection-js
homepage: https://github.com/ericsysmin/ansible-collection-js
issues: https://github.com/ericsysmin/ansible-collection-js/issues
