---
- name: NodeJS | Install dependent package
  ansible.builtin.apt:
    name:
      - gnupg
      - apt-transport-https

- name: NodeJS | Install the gpg key for nodejs LTS
  ansible.builtin.apt_key:
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: NodeJS | Install the NodeJS repository
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    filename: nodesource.list
    update_cache: true

- name: NodeJS | Install NodeJS package
  ansible.builtin.apt:
    name: nodejs
