galaxy_info:
  author: ericsysmin
  role_name: nodejs
  description: Role to install nodejs
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
  galaxy_tags: []
dependencies: []
