---
# code: language=ansible
- name: Yarn | Make sure HTTPS is supported by apt
  ansible.builtin.apt:
    name: apt-transport-https
    update_cache: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Yarn | Remove cmdtest
  ansible.builtin.apt:
    name: cmdtest
    state: absent
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: ansible_distribution_version is version("17.04", "==")

- name: Yarn | Import YARN APT key
  ansible.builtin.apt_key:
    url: "{{ yarn_debian_repo_gpg_key }}"
    state: present

- name: Yarn | Install YARN APT repo
  ansible.builtin.apt_repository:
    repo: deb {{ yarn_debian_repo_url }}
    filename: yarn
    state: present
