---
# code: language=ansible
- name: Yarn | Redhat | Install YARN YUM repo.
  ansible.builtin.yum_repository:
    name: yarn
    description: Yarn Repository
    baseurl: "{{ yarn_rhel_repo_url }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ yarn_rhel_repo_gpg_key }}"
    state: present

- name: Yarn | Redhat | Install NodeJS package for yarn dependency
  ansible.builtin.package:
    name: nodejs
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
