---
galaxy_info:
  author: ericsysmin
  role_name: yarn
  description: This role installs yarn on hosts.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      version:
        - jessie
        - stretch
  galaxy_tags:
    - centos
    - ubuntu
    - el
    - redhat
    - yarn
    - nodejs
    - node
dependencies: []
