name: "ericsysmin.js Lint"
on:
  push:
    paths:
      - 'roles/**'
      - 'molecule/**'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
      - 'roles/**'
      - 'molecule/**'
      - '.github/workflows/lint.yml'
jobs:
  nodejs:
    runs-on: ubuntu-20.04
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: true
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/ericsysmin/js

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible yamllint ansible-lint==5.4.0

      - name: Run role tests
        run: yamllint && ansible-lint
